### ISSUE TITLE
CNCF checklist

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#421]
Copy of https://github.com/cncf/toc/issues/531 for our tracking so we can mark off tasks

* [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
* [ ] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
* [ ] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy (See #420)
* [-] Has your project adopted open governance already? see http://opengovernance.dev

* [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list.
* [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
* [ ] Domain: transfer domain to CNCF/LF (ITx) 
* [ ] Trademarks: transfer any trademark and logo mark assets over to the LF - @natalisucks can probably help here
* [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
* [x] Artwork: Ensure logos present on https://github.com/cncf/artwork - (send)
* [x] Website: ensure LF footer is there and website guidelines followed https://github.com/wayfair-tremor/tremor-www-main/pull/10
* [x] Website: Analytics transferred - (we do not do analytics)
* [x] Devstats: add to devstats https://devstats.cncf.io/
* [ ] Marketing: update relevant intro + slide decks
* [-] Trail Map: update CNCF trail map if relevant (incubating projects and above)
* [ ] Update https://landscape.cncf.io
* [-] Events: update CFP + Registration + CFP Area forms
* [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
* [x] CNCF Welcome Email Sent to confirm maintainer list access
* [ ] Schedule monthly project sync with CNCF staff

Additions:
* [x] Make sure naming is vendor/organization neutral ( rename `wayfair-tremor` to a vendor neutral name )

Domain / website related:
* Slack migration to `slack.cncf.io`

**Comment by darach** [comment]
Tremor is now linked in the CNCF website on the sandbox projects page: https://www.cncf.io/sandbox-projects/ 🎸

**Comment by mfelsche** [comment]
The maintainer list doesnt seem to have been updated yet. Should we deliver it in some form or did this already happen, as that box is checked already?

**Comment by Licenser** [comment]
AFAIK the maintainer's list will be updated based on the CODEOWNERS file, at least that's what I understood based on @amye's request in the upstream ticket

**Comment by darach** [comment]
Organization renamed `tremor-rs` @caniszczyk

**Comment by caniszczyk** [comment]
@darach thanks let me know when you're ready to the domain transfer dance

**Comment by caniszczyk** [comment]
@darach also you will need to enable DCO checks https://github.com/apps/dco/ (assuming you have no CLA)

**Comment by Licenser** [comment]
DCO installed :)

**Comment by darach** [comment]
DCO we can enable in the morning @caniszczyk 👍

**Comment by darach** [comment]
@Licenser Stop working, get some rest

**Comment by Licenser** [comment]
Done :D
